%YAML 1.2
---
# Associative list in two forms:
# The first form is `symbol: hash`,
# where hash are key-value pairs
# That indicate the variations of the name associated with the symbol,
# such as ASCII form, true form, etc.
# If there's only one form, a bare string can be substituted in its place.
languages:
  # Main four
  EP: Egonyota Pasaru
  SX: Serakafph Xaxex
  EQ: {name: yukũa|Elaga ütæk|Qvaḻsa, ascii-name: yukua|Elaga utak|Qvalsa}
  Ct: Cipogrtesaj

  # PSD
  Yk: Yoskrai
  Ag: {name: Âagenzbèe, ascii-name: Aahqgenzbeeq}
  Cd: Cindri
  Rs: Rattssaw
  GE: Gwa-elohba
  NH: Nnn Heeel
  # Reserved for future use
  # Gb: Genbarg
  # Or: {name: Oraṕ, ascii-name: Oraf}

  # XAX
  Sk: Sekapon
  Ya: {name: Ya-kĕnaj, ascii-name: Ya-kewnaj}
  OF: Ouduec Fxelw

  # Others
  Ub: Uvbraot
  MGY: Man Gog Yuu
  AKF: Altrvukaif
  RDWA: {name: Rďƿa, ascii-name: Rdhwqa}

worlds:
  PSD: {name: Pseudo, true-name: Pasaru}
  XAX: Xaxex
  CIR: {name: Circular, true-name: Cipog}
  QUX: Quaxtion
  LEB: {name: Leħbraot, ascii-name: Lehqhbraot}
  BIG: Bigencenryin

special-tags:
  RSGN: Road signs
  OVEX: Octovexillology

---
# Ignore list.
# For each book (whose code is indicated by the key),
# a list of objects that indicate its ignorance.
# Lists indicate that the specified pages are ignored in that particular book,
# whereas true indicates the entire book is ignored.

boc:
  1: true
  2: true
  3: true
  4: true
  5: true
  6: [2, 3]
  7: [38, 39, 49]
  8: [21, 27, 28]
  9: [34, 37]
  10: [41]
  11: [2]
  13: [47]
  14: [29, 40]
  18: [15]
purple:
  1: [2]
