%YAML 1.2
---
# Associative list in two forms:
# The first form is `symbol: hash`,
# where hash are key-value pairs
# That indicate the variations of the name associated with the symbol,
# such as ASCII form, true form, etc.
# If there's only one form, a bare string can be substituted in its place.
languages:
  # Main four
  EP: Egonyota Pasaru
  SX: Serakafph Xaxex
  EQ: {name: yukũa|Elaga ütæk|Qvaḻsa, ascii-name: yukua|Elaga utak|Qvalsa}
  Ct: Cipogrtesaj

  # PSD
  Yk: Yoskrai
  Ag: {name: Âagenzbèe, ascii-name: Aahqgenzbeeq}
  Cd: Cindri
  Rs: Rattssaw
  GE: Gwa-elohba
  NH: Nnn Heeel
  # Reserved for future use
  # Gb: Genbarg
  # Or: {name: Oraṕ, ascii-name: Oraf}

  # XAX
  Sk: Sekapon
  Ya: {name: Ya-kĕnaj, ascii-name: Ya-kewnaj}
  OF: Ouduec Fxelw

  # Others
  Ub: Uvbraot
  MGY: Man Gog Yuu
  AKF: Altrvukaif
  RDWA: {name: Rďƿa, ascii-name: Rdhwqa}

worlds:
  PSD: {name: Pseudo, true-name: Pasaru}
  XAX: Xaxex
  CIR: {name: Circular, true-name: Cipog}
  QUX: Quaxtion
  LEB: {name: Leħbraot, ascii-name: Lehqhbraot}
  BIG: Bigencenryin

special-tags:
  RSGN: Road signs
  OVEX: Octovexillology

# --- # Maybe have this be a real document break in the future.
# Ignore list.
# For each book (whose code is indicated by the key),
# a list of objects that indicate its ignorance.
# Lists indicate that the specified pages are ignored in that particular book,
# whereas true indicates the entire book is ignored.

ignored:
  boc:
    - true
    - true
    - true
    - true
    - true # 5
    - [2, 3]
    - [38, 39, 49]
    - [21, 27, 28]
    - [34, 37]
    - [41] # 10
    - [2]
    - []
    - [47]
    - [29, 40]
    - [] # 15
    - []
    - []
    - [15]
  purple:
    - [2]
